In [3]:
#Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf
tf.__version__

'2.12.0'

In [4]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [5]:
#Encoding categorical data
#Label Encoding the "Gender" column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)
#One hot encoding the "geography" column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])],
                       remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(y)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [6]:
#Splitting the dataset into the training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2,
                                                    random_state=0) 

In [7]:
#Featurinf scaling
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

parte 2

In [8]:
#Iniatializing the ANN
ann = tf.keras.models.Sequential()

In [9]:
#Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [10]:
#Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [11]:
#Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

parte 3


In [12]:
# Compiling the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [13]:
# Training ANN on the training set
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6116 - accuracy: 0.6849
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4557 - accuracy: 0.8009
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4369 - accuracy: 0.8067
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4277 - accuracy: 0.8159
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4211 - accuracy: 0.8216
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4161 - accuracy: 0.8244
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4119 - accuracy: 0.8270
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4082 - accuracy: 0.8275
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4052 - accuracy: 0.8286
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4021 - accura

parte 4

In [14]:
#Predicting the result of a single observation
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))> 0.5)

1/1 [==============================] - 0s 77ms/step
[[False]]


In [15]:
# Predicting the test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),
                      y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 983us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [16]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1509   86]
 [ 202  203]]


0.856